---
title: 'Lab 7: Rank-based tests'
author: "An Bui"
date: "14 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

An made this repo and markdown doc!

I am Sam and I am a collaborator! I'm going to make some histograms

```{r}
library(tidyverse)
kermit <- read_csv("kermit.csv")

# Sam made a histogram
kermit_hist <- ggplot(kermit, aes(x = Score.pre)) +
  geom_histogram() +
  facet_wrap(~ Gender)

kermit_hist

# Was there a sig difference in kermit perception for pre-talk and post-talk scores?
```

An's going to do some rank-based tests.  

First, is there a significant difference in pre-talk Kermit scores for males and females?
```{r}
# values: Score.pre
# levels: Gender
# data are not paired because you're only looking at pre-talk for males and females
# therefore, use Mann-Whitney U


mwu_kermit <- kermit %>% 
  wilcox.test(Score.pre ~ Gender, 
              data = .) # message: cannot compute exact p-value with ties, which is fine - just a correction for ties

mwu_kermit
```
There is no significant difference in pre-talk Kermit ranks for males and females.













